import { notFound } from 'next/navigation'
import { getPublicDreamById } from '@/lib/supabase-server'
import { Metadata } from 'next'
import Image from 'next/image'

export async function generateMetadata({ params }: { params: { id: string } }): Promise<Metadata> {
  const id = params.id
  const dream = await getPublicDreamById(id)
  if (!dream) {
    return { title: 'Dream not found' }
  }
  const dreamNest = dream.dreams || {}
  const author = dream.users
  const title = `${author?.email?.split('@')[0] || 'Dreamer'}'s Dream`
  const desc = dreamNest?.text?.slice(0, 160) || 'Dream comic generated by The Dream Machine'
  const image = dreamNest?.panels?.[0]?.image_url || '/api/og'
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || (typeof window !== 'undefined' ? window.location.origin : '')
  const canonical = `${baseUrl}/public/dreams/${id}`

  return {
    title,
    description: desc,
    openGraph: {
      title,
      description: desc,
      images: [image],
      url: canonical,
    },
  }
}

export default async function DreamPublicPage({ params }: { params: { id: string } }) {
  const id = params.id
  const dream = await getPublicDreamById(id)
  if (!dream) return notFound()
  const dreamNest = dream.dreams || {}
  const author = dream.users

  return (
    <main className="max-w-4xl mx-auto p-8">
      <h1 className="text-3xl font-bold mb-4">{author?.email?.split('@')[0] || 'Dreamer'}'s Dream</h1>
      <p className="text-lg mb-6">{dreamNest?.text}</p>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {dreamNest?.panels?.map((p: any) => (
          <div key={p.id} className="rounded-lg overflow-hidden border" style={{ background: '#0a0118' }}>
            {p.image_url ? (
              <Image src={p.image_url} alt={p.description} width={600} height={400} sizes="(max-width: 768px) 100vw, 50vw" />
            ) : (
              <div className="p-6">{p.description}</div>
            )}
            <div className="p-3 text-sm text-gray-300">{p.description}</div>
          </div>
        ))}
      </div>
    </main>
  )
}
